WLAN: bcmdhd compilation fix
If bcmdhd is the only choosed wireless module (no b43, ...), compilation
fails on 'bcmdhd/wl_iw.c'.
drivers/net/wireless/bcmdhd/wl_iw.c:2958:2: error: unknown field
‘num_private’ specified in initializer
...
If we look at 'include/net/iw_handler.h' the private fields of the
struct iw_handler_def are only defined if 'CONFIG_WEXT_PRIV' is set.